services:
  undb:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - CDN_URL=${CDN_URL:-}
      # Add memory limit for the build process
      shm_size: '2gb'
    container_name: undb
    volumes:
      - .undb:/usr/src/app/.undb
    ports:
      - 3721:3721
    environment:
      # General Configuration
      - NODE_ENV=production
      - PORT=3721
      - NODE_OPTIONS=--max-old-space-size=4096
      - LOG_LEVEL=${LOG_LEVEL:-debug}
      - UNDB_BASE_URL=${UNDB_BASE_URL:-http://localhost:3721}
      
      # Database Configuration
      - UNDB_DB_PROVIDER=postgres
      - UNDB_DB_POSTGRES_URL=${UNDB_DB_POSTGRES_URL}
      
      # Storage Configuration
      - UNDB_STORAGE_PROVIDER=s3
      - UNDB_STORAGE_PRIVATE_BUCKET=${UNDB_STORAGE_PRIVATE_BUCKET:-undb-private}
      - UNDB_S3_STORAGE_ENDPOINT=${UNDB_S3_STORAGE_ENDPOINT:-s3.amazonaws.com}
      - UNDB_S3_STORAGE_REGION=${UNDB_S3_STORAGE_REGION:-us-east-1}
      - UNDB_S3_ACCESS_KEY_ID=${UNDB_S3_ACCESS_KEY_ID}
      - UNDB_S3_SECRET_ACCESS_KEY=${UNDB_S3_SECRET_ACCESS_KEY}
      - UNDB_MINIO_STORAGE_ENDPOINT=${UNDB_S3_STORAGE_ENDPOINT:-s3.amazonaws.com}
      - UNDB_MINIO_STORAGE_PORT=443
      - UNDB_MINIO_STORAGE_REGION=${UNDB_S3_STORAGE_REGION:-us-east-1}
      - UNDB_MINIO_STORAGE_USE_SSL=true
      - UNDB_MINIO_STORAGE_ACCESS_KEY=${UNDB_S3_ACCESS_KEY_ID}
      - UNDB_MINIO_STORAGE_SECRET_KEY=${UNDB_S3_SECRET_ACCESS_KEY}
      
      # Email Configuration
      - UNDB_MAIL_PROVIDER=${UNDB_MAIL_PROVIDER:-nodemailer}
      - UNDB_MAIL_HOST=${UNDB_MAIL_HOST:-email-smtp.us-west-1.amazonaws.com}
      - UNDB_MAIL_PORT=${UNDB_MAIL_PORT:-465}
      - UNDB_MAIL_SECURE=${UNDB_MAIL_SECURE:-true}
      - UNDB_MAIL_USER=${UNDB_MAIL_USER}
      - UNDB_MAIL_PASS=${UNDB_MAIL_PASS}
      - UNDB_MAIL_DEFAULT_FROM=${UNDB_MAIL_DEFAULT_FROM:-no-reply@yourdomain.com}
      
      # Application Configuration
      - UNDB_DISABLE_REGISTRATION=${UNDB_DISABLE_REGISTRATION:-true}
      - UNDB_ADMIN_EMAIL=${UNDB_ADMIN_EMAIL:-admin@undb.io}
      - UNDB_ADMIN_PASSWORD=${UNDB_ADMIN_PASSWORD:-admin}
    restart: unless-stopped
    # Add memory limit for the running container
    mem_limit: 2g
healthcheck:
  test: ["CMD", "wget", "-q", "--spider", "http://localhost:3721/health"]
  # Or use this alternative if wget isn't available either
  # test: ["CMD-SHELL", "bun --eval 'fetch(\"http://localhost:3721/health\").then(r => process.exit(r.ok ? 0 : 1)).catch(() => process.exit(1))'"]
  interval: 30s
  timeout: 10s
  retries: 3
  start_period: 40s

volumes:
  .undb:
